"""Quiet hours replace bedroom mode.

Bedroom mode did two things: it dimmed the display over a window of the day,
and it silenced the reminders that fell inside it. NG makes the first one a
setting — `minBrightness` in `/api/v1/system`, measured: in a dark room the
panel sits exactly on that floor, and lowering it takes the display with it.
So the dimming, the saved settings and the restore all go, and what is left is
the half a light sensor cannot do.

**This migration is written by hand, and the autogenerated version was wrong
twice.**

First, it added `quiet_hours NOT NULL` with no default, which fails on a table
that already has rows — and by the time anyone reads this, it does.

Second and worse, SQLite has no DROP COLUMN worth the name, so Alembic rebuilds
the table: create, copy, **drop the old one**, rename. The application runs
with `PRAGMA foreign_keys=ON` (see `app/db/session.py`), and `widget_target`
and `reminder_target` both reference `device.id` with ON DELETE CASCADE. That
drop therefore takes every row of both with it — silently, no error, just
widgets attached to no display. It is precisely how awtrixhub shipped a broken
migration once, and the reason `tests/test_migrations.py` runs these through
`init_db()` rather than through the Alembic CLI.

So the pragma is turned off around the rebuild. SQLite refuses to change it
inside a transaction; this works because Alembic runs SQLite migrations with
non-transactional DDL, which its own log says on every start.

Revision ID: 30ca1cb373ca
Revises: 6976918846d4
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "30ca1cb373ca"
down_revision: str | None = "6976918846d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    bind.exec_driver_sql("PRAGMA foreign_keys=OFF")
    try:
        # 1. The new columns, with defaults so existing rows are valid.
        with op.batch_alter_table("device", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "quiet_hours",
                    sa.Boolean(),
                    nullable=False,
                    server_default=sa.false(),
                )
            )
            batch_op.add_column(sa.Column("quiet_from", sa.Time(), nullable=True))
            batch_op.add_column(sa.Column("quiet_to", sa.Time(), nullable=True))

        # 2. Carry the window over. Only the window: the brightness, the saved
        #    settings and the active flag have nowhere to go, which is the
        #    point of the change.
        bind.exec_driver_sql(
            "UPDATE device SET quiet_hours = night_mode,"
            " quiet_from = night_from, quiet_to = night_to"
        )

        # 3. Only now drop the old ones.
        with op.batch_alter_table("device", schema=None) as batch_op:
            for column in (
                "night_mode",
                "night_from",
                "night_to",
                "night_brightness",
                "night_active",
                "night_saved",
            ):
                batch_op.drop_column(column)
    finally:
        bind.exec_driver_sql("PRAGMA foreign_keys=ON")


def downgrade() -> None:
    """Back to bedroom mode, minus what it cannot know.

    The window comes back. The brightness returns to its old default and the
    saved settings do not return at all — they described a state of the display
    that this version never wrote, and inventing one would be worse than the
    default.
    """
    bind = op.get_bind()
    bind.exec_driver_sql("PRAGMA foreign_keys=OFF")
    try:
        with op.batch_alter_table("device", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "night_mode", sa.Boolean(), nullable=False, server_default=sa.false()
                )
            )
            batch_op.add_column(sa.Column("night_from", sa.Time(), nullable=True))
            batch_op.add_column(sa.Column("night_to", sa.Time(), nullable=True))
            batch_op.add_column(
                sa.Column(
                    "night_brightness",
                    sa.Integer(),
                    nullable=False,
                    server_default=sa.text("1"),
                )
            )
            batch_op.add_column(
                sa.Column(
                    "night_active", sa.Boolean(), nullable=False, server_default=sa.false()
                )
            )
            batch_op.add_column(sa.Column("night_saved", sa.String(), nullable=True))

        bind.exec_driver_sql(
            "UPDATE device SET night_mode = quiet_hours,"
            " night_from = quiet_from, night_to = quiet_to"
        )

        with op.batch_alter_table("device", schema=None) as batch_op:
            for column in ("quiet_hours", "quiet_from", "quiet_to"):
                batch_op.drop_column(column)
    finally:
        bind.exec_driver_sql("PRAGMA foreign_keys=ON")
