"""Initial schema.

One migration, not the thirteen awtrixhub accumulated. Its history is its own:
it records, among other things, the day reminders gained centring and rainbow
text — two options AWTRIX NG does not have. Replaying someone else's past to
arrive at a schema we would then have to correct would be ceremony, not
safety. This project starts here.

Revision ID: 6976918846d4
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '6976918846d4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('secrets', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'HEALTHY', 'DEGRADED', 'ERROR', 'DISABLED', name='healthstatus'), nullable=False),
    sa.Column('last_success', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_type'), ['type'], unique=False)

    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('firmware', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('UNKNOWN', 'HEALTHY', 'DEGRADED', 'ERROR', 'DISABLED', name='healthstatus'), nullable=False),
    sa.Column('last_seen', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('night_mode', sa.Boolean(), nullable=False),
    sa.Column('night_from', sa.Time(), nullable=True),
    sa.Column('night_to', sa.Time(), nullable=True),
    sa.Column('night_brightness', sa.Integer(), nullable=False),
    sa.Column('night_saved', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('night_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_name'), ['name'], unique=False)

    op.create_table('reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('at', sa.Time(), nullable=False),
    sa.Column('every_weeks', sa.Integer(), nullable=False),
    sa.Column('anchor', sa.Date(), nullable=True),
    sa.Column('on_date', sa.Date(), nullable=True),
    sa.Column('countdown_to', sa.Date(), nullable=True),
    sa.Column('weekdays', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('scroll_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scroll_speed', sa.Integer(), nullable=False),
    sa.Column('background', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('repeat_count', sa.Integer(), nullable=False),
    sa.Column('repeat_every_minutes', sa.Integer(), nullable=False),
    sa.Column('rings_at_night', sa.Boolean(), nullable=False),
    sa.Column('melody', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_fired_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_name'), ['name'], unique=False)

    op.create_table('setting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('reminder_target',
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reminder_id', 'device_id')
    )
    op.create_table('widget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('widget_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('display', sa.JSON(), nullable=True),
    sa.Column('refresh_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'HEALTHY', 'DEGRADED', 'ERROR', 'DISABLED', name='healthstatus'), nullable=False),
    sa.Column('last_success', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connector.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_widget_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_widget_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_widget_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_widget_widget_type'), ['widget_type'], unique=False)

    op.create_table('widget_target',
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'HEALTHY', 'DEGRADED', 'ERROR', 'DISABLED', name='healthstatus'), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_pushed_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_id'], ['widget.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('widget_id', 'device_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('widget_target')
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_widget_widget_type'))
        batch_op.drop_index(batch_op.f('ix_widget_position'))
        batch_op.drop_index(batch_op.f('ix_widget_name'))
        batch_op.drop_index(batch_op.f('ix_widget_connector_id'))

    op.drop_table('widget')
    op.drop_table('reminder_target')
    op.drop_table('setting')
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_name'))

    op.drop_table('reminder')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_name'))

    op.drop_table('device')
    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_type'))
        batch_op.drop_index(batch_op.f('ix_connector_name'))

    op.drop_table('connector')
    # ### end Alembic commands ###
